package com.crocket.model;

import static com.crocket.shared.SurfaceType.*;

import com.crocket.model.entity.Hoop;
import com.crocket.model.entity.Peg;
import com.crocket.model.entity.Stone;
import com.crocket.shared.Direction;
import com.crocket.shared.SurfaceType;

/**
 * Represents Level 1 in the game.
 * Extends the abstract class Level.
 */
public class Level1 extends Level {
    private static int width = 25;
    private static int height = 15;
    private static final int STONEWIDTH = 30;
    private static final int STONEHEIGHT = 30;
    private static final int HOOPHEIGHT = 20;
    private static final int HOOPWIDTH = 40;
    private static final int HOOPOPENINGWIDTH = 32;
    private static final int HOOPOPENINGHEIGHT = 4;
    private static final int PEGWIDTH = 5;
    private static final int PEGHEIGHT = 40;
 
    private static SurfaceType[][] tilemap = {
            { GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS},
            { GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS },
            { GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS },
            { GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, ICE, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS },
            { GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, ICE, ICE, ICE, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS },
            { GRASS, GRASS, GRASS, GRASS, GRASS, ICE, ICE, ICE, ICE, ICE, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS },
            { GRASS, GRASS, GRASS, GRASS, ICE, ICE, ICE, ICE, ICE, ICE, ICE, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS },
            { GRASS, GRASS, GRASS, GRASS, GRASS, ICE, ICE, ICE, ICE, ICE, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND },
            { GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, ICE, ICE, ICE, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND, SAND, SAND },
            { GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, ICE, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND, SAND, SAND, SAND },
            { GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND, SAND, SAND, SAND, SAND },
            { GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND, SAND, SAND, SAND, SAND, SAND, SAND, SAND, SAND, SAND, GRASS },
            { GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND, SAND, SAND, SAND, SAND, SAND, SAND, SAND, SAND, SAND, GRASS, GRASS, GRASS },
            { GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND, SAND, SAND, SAND, SAND, SAND, SAND, SAND, SAND, SAND, SAND, GRASS, GRASS, GRASS },
            { GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND, SAND, SAND, SAND, SAND,SAND, SAND, SAND, SAND, SAND, SAND, GRASS, GRASS, GRASS, GRASS} };

    private static Stone[] stoneList = {
            new Stone(STONEWIDTH, STONEHEIGHT, 600, 500), new Stone(STONEWIDTH, STONEHEIGHT, 600, 600 ), new Stone(STONEWIDTH, STONEHEIGHT, 666, 667),
            new Stone(STONEWIDTH, STONEHEIGHT, 669, 5), new Stone(STONEWIDTH, STONEHEIGHT,2, 240), new Stone(STONEWIDTH, STONEHEIGHT, 1200, 650),
            new Stone(STONEWIDTH, STONEHEIGHT, 643, 390), new Stone(STONEWIDTH, STONEHEIGHT, 695, 196), new Stone(STONEWIDTH, STONEHEIGHT, 1016, 192),
            new Stone(STONEWIDTH, STONEHEIGHT, 635, 85), new Stone(STONEWIDTH, STONEHEIGHT, 391, 645), new Stone(STONEWIDTH, STONEHEIGHT, 904, 302),
            new Stone(STONEWIDTH, STONEHEIGHT, 1148, 387), new Stone(STONEWIDTH, STONEHEIGHT, 573, 444), new Stone(STONEWIDTH, STONEHEIGHT, 1229, 613),
            new Stone(STONEWIDTH, STONEHEIGHT, 95, 158), new Stone(STONEWIDTH, STONEHEIGHT, 340, 512), new Stone(STONEWIDTH, STONEHEIGHT, 1124, 653),
            new Stone(STONEWIDTH, STONEHEIGHT, 1038, 680), new Stone(STONEWIDTH, STONEHEIGHT, 1246, 461), new Stone(STONEWIDTH, STONEHEIGHT, 652, 522),
            new Stone(STONEWIDTH, STONEHEIGHT, 697, 434), new Stone(STONEWIDTH, STONEHEIGHT, 1159, 616), new Stone(STONEWIDTH, STONEHEIGHT, 848, 100),
    };

    private static Hoop[] hoopsList = {
            new Hoop(HOOPWIDTH, HOOPHEIGHT, HOOPOPENINGWIDTH, HOOPOPENINGHEIGHT, 295, 450, Direction.SOUTH), new Hoop(HOOPWIDTH, HOOPHEIGHT, HOOPOPENINGWIDTH, HOOPOPENINGHEIGHT, 400, 600, Direction.EAST),
            new Hoop(HOOPWIDTH, HOOPHEIGHT, HOOPOPENINGWIDTH, HOOPOPENINGHEIGHT, 900, 350, Direction.NORTH), new Hoop(HOOPWIDTH, HOOPHEIGHT, HOOPOPENINGWIDTH, HOOPOPENINGHEIGHT, 750, 200, Direction.WEST),
            new Hoop(HOOPWIDTH, HOOPHEIGHT, HOOPOPENINGWIDTH, HOOPOPENINGHEIGHT, 1000, 250, Direction.EAST), new Hoop(HOOPWIDTH, HOOPHEIGHT, HOOPOPENINGWIDTH, HOOPOPENINGHEIGHT, 600, 300, Direction.EAST),
            new Hoop(HOOPWIDTH, HOOPHEIGHT, HOOPOPENINGWIDTH, HOOPOPENINGHEIGHT, 300, 150, Direction.SOUTH), new Hoop(HOOPWIDTH, HOOPHEIGHT, HOOPOPENINGWIDTH, HOOPOPENINGHEIGHT, 150, 276, Direction.SOUTH),
            new Hoop(HOOPWIDTH, HOOPHEIGHT, HOOPOPENINGWIDTH, HOOPOPENINGHEIGHT, 500, 450, Direction.NORTH), new Hoop(HOOPWIDTH, HOOPHEIGHT, HOOPOPENINGWIDTH, HOOPOPENINGHEIGHT, 800, 500, Direction.SOUTH)
    };

    public Level1() {
        super(width, height, tilemap);

        for(Stone stone : stoneList){
            addStone(stone);
        }
        for (Hoop hoop : hoopsList){
            addHoop(hoop);
        }
        Peg p = new Peg(PEGWIDTH, PEGHEIGHT, 309, 100);
        addPeg(p);
    }

    public Level1(Level1 levelCopy){
        super(levelCopy);
    }
}
